# Generated by Django 3.2 on 2023-01-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='events',
            name='banner',
            field=models.ImageField(default=1, upload_to='banner/', verbose_name='Banner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='cover',
            field=models.ImageField(default=1, help_text='210x300', upload_to='cover/', verbose_name='Imagen Representativa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
