# Generated by Django 3.2 on 2023-01-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20230111_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='cover',
            field=models.ImageField(help_text='360x220', upload_to='cover/', verbose_name='Imagen Representativa'),
        ),
    ]
