# Generated by Django 3.2 on 2023-01-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20230111_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='url',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
