# Generated by Django 3.2 on 2023-01-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderusers_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderusers',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Info'},
        ),
        migrations.AlterField(
            model_name='orderusers',
            name='document',
            field=models.CharField(max_length=255, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='orderusers',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='orderusers',
            name='first_name',
            field=models.CharField(max_length=120, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='orderusers',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='orderusers',
            name='type_document',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CE', 'CE')], max_length=255, verbose_name='Tipo de documento'),
        ),
    ]
